---
- name: pfsenseConfiguration
  hosts: pfswitch

# Module Runner
  tasks:
    - include: ../mirahiModule/privilegeInstall.yml
    - include: ../mirahiModule/hostname.yml
    - include: ../mirahiModule/firewallNoPing.yml