---
- name: pfsenseConfiguration
  hosts: pfswitch

# Module Runner
  tasks:
    - include: ../modules/privilegeInstall.yml
    - include: ../modules/hostname.yml
    - include: ../modules/firewallNoPing.yml