---
- name: pfsenseConfiguration
  hosts: pfswitch

# Module Runner
  tasks:
    - include: ../modules/package/privilegeInstall.yml
    - include: ../modules/general/hostname.yml
    - include: ../modules/firewall/noPing.yml