---

- name: pfsenseConfiguration
  hosts: pfswitch

  tasks:
#REQUIRED PKG FOR MANAGEMENT
  - name: install sudo pkg on pfsense
    package:
      name:
        - sudo
      state: latest
      check_mode: yes

#CHANGE HOSTNAME 
  - name: pfsensible_hostname
    pfsensible.core.pfsense_setup:
      hostname: PF_Loic
      domain: mirahi.local
      check_mode: yes

#FIREWALL RULE : No Ping
  - name: pfsensible_firewallRule
    pfsensible.core.pfsense_rule:
      name: 'NoPing'
      action: block
      interface: lan
      ipprotocol: inet
      protocol: icmp
      source: any
      destination: any   
      after: top
      check_mode: yes
