---
- name: pfsenseConfiguration
  hosts: pfswitch

# Module Runner
  tasks:
    - include: ../module/package/sudo.yml
    - include: ../module/general/hostname.yml
    - include: ../module/interface/assign.yml
    - include: ../module/interface/vlan.yml 
    # - include: ../module/interface/group.yml
    - include: ../module/general/timezone_lang.yml
    - include: ../module/firewall/noPing.yml
    - include: ../module/service/dns.yml
