---

- name: pfsenseConfiguration
  hosts: pfswitch

  tasks:
    - include: ../mirahiModule/privilegeInstall.yml
    - include: ../mirahiModule/hostname.yml
    - include: ../mirahiModule/firewallNoPing.yml