---
- name: pfsenseSudo
  hosts: ssh-server

  tasks:
  - name: install sudo pkg on pfsense
    package:
      name:
        - sudo
      state: latest

  - name: add adservers alias
    ansible.builtin.hostname:
      name: adservers
      address: pfloic
      state: present
      use: systemd

