---

- name: This is a hello-world example
  hosts: all
  tasks:
# SIMPLE TEXT CREATION WITH CONTENT 
    # - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    #   copy:
    #     content: hello-world
    #     dest: $HOME/testfile.txt
    #     mode: 0644


- name: pfsenseConfiguration
  hosts: pfswitch
  
  tasks:
  - name: install sudo pkg on pfsense
    package:
      name:
        - sudo
      state: latest

# # change hostname OK
  - name: pfsensible_hostname
    pfsensible.core.pfsense_setup:
      hostname: PF_Loic
      domain: mirahi.local

#FIREWALL RULE : block the ping OK 
  - name: pfsensible_firewallRule
    pfsensible.core.pfsense_rule:
      name: 'NoPing'
      action: block
      interface: lan
      ipprotocol: inet
      protocol: icmp
      source: any
      destination: any   
      after: top
