name: GitHub Action entrypoints
on:
  push:
    branches:
      - main

jobs:
  ansible:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run playbook
        run: |
          git clone https://github.com/loictlpk/ghaTest.git
          ansible-playbook -i ./ansible/playbook.yml ./ansible/inventory.yml
