name: GitHub Action entrypoints
on:
  push:
    branches: [main]

jobs:
  MyCheckout:
    defaults:
      run:
        working-directory: ./ansible/
    runs-on: self-hosted
    steps:
      - name: Setup checkout environment
        uses: actions/checkout@v3

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ../ansible/inventory.yml ../ansible/playbook.yml