name: test
on: [push]
  
jobs:
  clone:
    runs-on: self-hosted
    steps:
      - name: Run a multi-line script
        run: |
          git clone https://github.com/loictlpk/ghaTest.git $HOME
          