name: test
on: [push]
  
jobs:
  clone:
    runs-on: self-hosted
    steps:
      - name: clone repo and replace 
        run: |
          git clone https://github.com/loictlpk/ghaTest.git $HOME/pf
          ansible all -i inventory.yml -m ping

