name: test
on: [push]
  
jobs:
  clone:
    runs-on: self-hosted
    steps:
      - name: clone repo and replace 
        run: |
          cd $HOME
          git clone https://github.com/loictlpk/ghaTest.git $HOME/pf

          